# -*- coding: utf-8 -*-
"""Language_Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jMySLfJSVjpHBM3qBUxcYplf1B03tsv
"""

!pip install transformers

!pip install sentencepiece

!pip install transformers --upgrade
!pip install sentencepiece --upgrade

from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

#article_hi = "संयुक्त राष्ट्र के प्रमुख का कहना है कि सीरिया में कोई सैन्य समाधान नहीं है"
#article_hi = "मैं खुश हूँ।"
#article_hi = "मैं रोज़ाना सुबह जॉगिंग करता हूँ।"
#article_hi = "उनके पास संविदानिक हक है कि वे स्वतंत्रता के साथ जीवन जीने, विचार करने और धार्मिकता का आदर करने का अधिकार रखें।"
#article_hi = "बचा"
article_hi = "बादलों की छायांकना मेरी मनमोहक छुट्टी को और भी रोमांचक बना दिया, जब मैंने वर्षों बाद अपने गांव लौटकर उन पहाड़ियों की चोटियों पर चढ़ने का साहस किया।"

model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-many-to-many-mmt")

tokenizer.src_lang = "ar_AR"
encoded_hi = tokenizer(article_hi, return_tensors="pt")
generated_tokens = model.generate(**encoded_hi, forced_bos_token_id=tokenizer.lang_code_to_id["en_XX"])
tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)